name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'develop'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn install --frozen-lockfile
    - run: yarn run test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: ./
      with:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        LABEL_SETTING_FILE_PATH: './.github/semantic_versioning_label.json'
        TAG_TO: 'origin/develop'
        DRY_RUN: 'true'
        COMMENT_ON_PR: 'false'
